[Appearance]
color_scheme_path=/home/sn0w/.config/qt5ct/colors/custom.conf
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=Qt5 QSettings

[Fonts]
fixed=Adwaita Mono,10,-1,5,50,0,0,0,0,0
general=Adwaita Mono,10,-1,5,50,0,0,0,0,0
