general {
    lock_cmd = notify-send "Locking..." # cmd to lock the screen
    lock_timeout = 300 # seconds until the lock cmd is ran after idle
    before_sleep_cmd = systemctl suspend # cmd to run before sleep
    ignore_if_shutdown = true
}

listener {
    timeout = 300 # seconds until idle
    on_timeout = systemctl suspend
}

listener {
    timeout = 600 # seconds until idle
    on_timeout = swaylock
}
