$accent  = rgb(ffffff)
$surface = rgb(1e1e2e)   # waybar background
$text    = rgb(ffffff)
$red     = rgb(f38ba8)   # waybar battery color
$yellow  = rgb(f9e2af)   # waybar wireplumber color
$font    = JetBrainsMono Nerd Font

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND use wallpaper
#background {
#  monitor = 
#  path = $HOME/Pictures/wallpapers/minimalno.png
#  blur_size = 5
#  blur_passes = 3
# brightness = 0.4
#}

# BACKGROUND use screenshot
background {
  monitor =
  path = $HOME/.cache/lockscreen.png
  blur_size = 5
  blur_passes = 3
  brightness = 0.4
}

# INPUT FIELD
input-field {
  monitor =
  size = 350, 50
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface
  font_color = $text
  fade_on_empty = false
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
